### ISSUE TITLE
#1 Edição do PHP Sem Arrudeios - CallForPaper

### ISSUE THREAD

**Issue by ghost** [Arretadas-do-PHP/PHP-Sem-Arrudeios#1]
Olá, povo bonito!
Essa é a Issue destinada para a realização do call 4 papers para a primeira edição do PHP sem Arrudeios de 2020 que acontecerá no dia 29 de fevereiro.

Algumas observações:
1: Somente 2 serão escolhidas, as que tiverem maior quantidade de reações nesta issue.
2: Palestrante precisa estar disponível das 13 as 17h
3: Votações serão válidas até dia 01/02 para divulgação até o dia 05/02

O modelo para submissão de talk é o seguinte:
[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

Contamos com a sua participação! 🖥<3

**Comment by rafaelabritto** [comment]
[Rafaela Brito] - [Identificando vulnerabilidades no desenvolvimento de aplicações web]
[Nós sabemos que a segurança da informação é pré-requisito ao desenvolvedor, que tal então relembrar a ISO 27002? Já pensou em identificar as vulnerabilidades do seu código de forma automatizada?
Nessa palestra de forma simples e resumida, vou te apresentar dicas de como entregar uma aplicação mais segura, facilitando seu trabalho não só para identificar, mas também tratar as vulnerabilidades encontradas.]

**Comment by dersonsena** [comment]
Kilderson Sena - Eu sei que POO é a pedra do teu sapato

Muitos desenvolvedores, em pleno século XXI, ainda tem muitas dificuldades de entender OO. O objetivo dessa talk é te dá uma boa base dos pilares do paradigma da Orientação a Objetos, e conseguir a partir daqui caminhar sozinho nos seus estudos. Será mostrado com exemplos bem divertidos, descontraídos e, principalmente, com muito código para que seja REALMENTE aprenda.

Talvez com essa talk vocês comecem a desenvolver como gente grande e você tire essa(s) pedra(s) no teu sapado que te atormentam todos os dias. =D

**Comment by rebeca-maia** [comment]
[Rebeca Maia Pontes] - Como aprimorar suas _Soft Skills_ no mercado de TI

Atualmente, possuir apenas conhecimentos técnicos (hard skills) não é o suficiente para garantir seu sucesso no mercado de trabalho ou conseguir uma vaga na sua empresa dos sonhos. As _hard skills_ podem ser adquiridas através da faculdade, de cursos online, da experiência em desenvolvimentos de projetos anteriores. É claro que as soft skills também podem ser ensinadas, treinadas e desenvolvidas, mas esse é um processo muito mais demorado, pois isso envolve diretamente a personalidade da pessoa e a habilidade dela de se conectar com outras pessoas a fim de atingir um objetivo.  É com as soft skills que você mostra como lida com os desafios do dia a dia. Nessa palestra abordarei o que são soft skills e como seu uso pode impactar seu trabalho.
